# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

[flavor]
dark = "kanagawa"

[icon]
files = [
	{ name = ".bash_profile", text = "", fg = "#40a02b" },
	{ name = ".bashrc", text = "", fg = "#40a02b" },
	{ name = ".gitconfig", text = "", fg = "#d20f39" },
	{ name = ".gitignore", text = "", fg = "#d20f39" },
	{ name = ".vimrc", text = "", fg = "#40a02b" },
	{ name = ".Xauthority", text = "", fg = "#d20f39" },
	{ name = ".xinitrc", text = "", fg = "#d20f39" },
	{ name = ".Xresources", text = "", fg = "#d20f39" },
	{ name = ".xsession", text = "", fg = "#d20f39" },
	{ name = "AUTHORS", text = "", fg = "#1e66f5" },
	{ name = "AUTHORS.txt", text = "", fg = "#1e66f5" },
	{ name = "build", text = "", fg = "#40a02b" },
	{ name = "config", text = "", fg = "#5c5f77" },
	{ name = "copying", text = "", fg = "#df8e1d" },
	{ name = "favicon.ico", text = "", fg = "#df8e1d" },
	{ name = "i3blocks.conf", text = "", fg = "#5c5f77" },
	{ name = "i3status.conf", text = "", fg = "#5c5f77" },
	{ name = "index.theme", text = "", fg = "#40a02b" },
	{ name = "license", text = "", fg = "#df8e1d" },
	{ name = "license.md", text = "", fg = "#df8e1d" },
	{ name = "makefile", text = "", fg = "#5c5f77" },
	{ name = "mpv.conf", text = "", fg = "#8839ef" },
	{ name = "PKGBUILD", text = "", fg = "#1e66f5" },
	{ name = "readme", text = "", fg = "#5c5f77" },
	{ name = "readme.md", text = "", fg = "#5c5f77" },
	{ name = "rmd", text = "", fg = "#1e66f5" },
	{ name = "security", text = "", fg = "#5c5f77" },
	{ name = "security.md", text = "", fg = "#5c5f77" },
	{ name = "tmux.conf", text = "", fg = "#40a02b" },
	{ name = "tmux.conf.local", text = "", fg = "#40a02b" },
	{ name = "xorg.conf", text = "", fg = "#d20f39" },
]
exts = [
	{ name = "7z", text = "", fg = "#df8e1d" },
	{ name = "aac", text = "", fg = "#1e66f5" },
	{ name = "android", text = "", fg = "#40a02b" },
	{ name = "ape", text = "", fg = "#1e66f5" },
	{ name = "apk", text = "", fg = "#40a02b" },
	{ name = "app", text = "", fg = "#d20f39" },
	{ name = "bak", text = "", fg = "#5c5f77" },
	{ name = "bash", text = "", fg = "#40a02b" },
	{ name = "bat", text = "", fg = "#df8e1d" },
	{ name = "bin", text = "", fg = "#d20f39" },
	{ name = "bmp", text = "", fg = "#ea76cb" },
	{ name = "bz", text = "", fg = "#df8e1d" },
	{ name = "bz2", text = "", fg = "#df8e1d" },
	{ name = "bz3", text = "", fg = "#df8e1d" },
	{ name = "c", text = "", fg = "#1e66f5" },
	{ name = "c++", text = "", fg = "#8839ef" },
	{ name = "cache", text = "", fg = "#5c5f77" },
	{ name = "cc", text = "", fg = "#8839ef" },
	{ name = "ccm", text = "", fg = "#8839ef" },
	{ name = "cfg", text = "", fg = "#5c5f77" },
	{ name = "cmake", text = "", fg = "#5c5f77" },
	{ name = "conf", text = "", fg = "#5c5f77" },
	{ name = "cp", text = "", fg = "#1e66f5" },
	{ name = "cpp", text = "", fg = "#1e66f5" },
	{ name = "cppm", text = "", fg = "#1e66f5" },
	{ name = "cpy", text = "", fg = "#1e66f5" },
	{ name = "css", text = "", fg = "#8839ef" },
	{ name = "csv", text = "", fg = "#40a02b" },
	{ name = "cue", text = "", fg = "#e64553" },
	{ name = "db", text = "", fg = "#5c5f77" },
	{ name = "desktop", text = "", fg = "#8839ef" },
	{ name = "diff", text = "", fg = "#5c5f77" },
	{ name = "dll", text = "", fg = "#d20f39" },
	{ name = "doc", text = "", fg = "#1e66f5" },
	{ name = "docx", text = "", fg = "#1e66f5" },
	{ name = "download", text = "", fg = "#179299" },
	{ name = "dump", text = "", fg = "#5c5f77" },
	{ name = "ebook", text = "", fg = "#df8e1d" },
	{ name = "eot", text = "", fg = "#5c5f77" },
	{ name = "epub", text = "", fg = "#df8e1d" },
	{ name = "exe", text = "", fg = "#d20f39" },
	{ name = "fish", text = "", fg = "#5c5f77" },
	{ name = "flac", text = "", fg = "#1e66f5" },
	{ name = "flc", text = "", fg = "#5c5f77" },
	{ name = "gif", text = "", fg = "#ea76cb" },
	{ name = "git", text = "", fg = "#d20f39" },
	{ name = "gz", text = "", fg = "#df8e1d" },
	{ name = "h", text = "", fg = "#ea76cb" },
	{ name = "hex", text = "", fg = "#1e66f5" },
	{ name = "hh", text = "", fg = "#ea76cb" },
	{ name = "hpp", text = "", fg = "#ea76cb" },
	{ name = "htm", text = "", fg = "#d20f39" },
	{ name = "html", text = "", fg = "#d20f39" },
	{ name = "ico", text = "", fg = "#df8e1d" },
	{ name = "ics", text = "", fg = "#1e66f5" },
	{ name = "image", text = "", fg = "#5c5f77" },
	{ name = "img", text = "", fg = "#5c5f77" },
	{ name = "import", text = "", fg = "#5c5f77" },
	{ name = "info", text = "", fg = "#5c5f77" },
	{ name = "ini", text = "", fg = "#5c5f77" },
	{ name = "iso", text = "", fg = "#5c5f77" },
	{ name = "jar", text = "", fg = "#df8e1d" },
	{ name = "java", text = "", fg = "#d20f39" },
	{ name = "jpeg", text = "", fg = "#ea76cb" },
	{ name = "jpg", text = "", fg = "#ea76cb" },
	{ name = "js", text = "", fg = "#df8e1d" },
	{ name = "json", text = "", fg = "#df8e1d" },
	{ name = "json5", text = "", fg = "#df8e1d" },
	{ name = "jsonc", text = "", fg = "#df8e1d" },
	{ name = "less", text = "", fg = "#8839ef" },
	{ name = "lib", text = "", fg = "#d20f39" },
	{ name = "license", text = "", fg = "#df8e1d" },
	{ name = "lock", text = "", fg = "#5c5f77" },
	{ name = "log", text = "", fg = "#5c5f77" },
	{ name = "lrc", text = "", fg = "#df8e1d" },
	{ name = "lua", text = "", fg = "#1e66f5" },
	{ name = "luac", text = "", fg = "#1e66f5" },
	{ name = "luau", text = "", fg = "#04a5e5" },
	{ name = "m3u", text = "", fg = "#e64553" },
	{ name = "m3u8", text = "", fg = "#e64553" },
	{ name = "m4a", text = "", fg = "#1e66f5" },
	{ name = "makefile", text = "", fg = "#5c5f77" },
	{ name = "markdown", text = "", fg = "#5c5f77" },
	{ name = "md", text = "", fg = "#5c5f77" },
	{ name = "md5", text = "", fg = "#8839ef" },
	{ name = "mkv", text = "", fg = "#df8e1d" },
	{ name = "mobi", text = "", fg = "#df8e1d" },
	{ name = "mojo", text = "", fg = "#d20f39" },
	{ name = "mov", text = "", fg = "#df8e1d" },
	{ name = "mp3", text = "", fg = "#1e66f5" },
	{ name = "mp4", text = "", fg = "#df8e1d" },
	{ name = "mpp", text = "", fg = "#1e66f5" },
	{ name = "nix", text = "", fg = "#1e66f5" },
	{ name = "o", text = "", fg = "#d20f39" },
	{ name = "obj", text = "", fg = "#5c5f77" },
	{ name = "odf", text = "", fg = "#8839ef" },
	{ name = "ogg", text = "", fg = "#1e66f5" },
	{ name = "opus", text = "", fg = "#1e66f5" },
	{ name = "org", text = "", fg = "#5c5f77" },
	{ name = "otf", text = "", fg = "#5c5f77" },
	{ name = "part", text = "", fg = "#179299" },
	{ name = "patch", text = "", fg = "#5c5f77" },
	{ name = "pdf", text = "", fg = "#d20f39" },
	{ name = "php", text = "", fg = "#ea76cb" },
	{ name = "png", text = "", fg = "#ea76cb" },
	{ name = "ppt", text = "", fg = "#d20f39" },
	{ name = "pptx", text = "", fg = "#d20f39" },
	{ name = "pub", text = "", fg = "#5c5f77" },
	{ name = "pxd", text = "", fg = "#1e66f5" },
	{ name = "pxi", text = "", fg = "#1e66f5" },
	{ name = "py", text = "", fg = "#df8e1d" },
	{ name = "pyc", text = "", fg = "#5c5f77" },
	{ name = "pyd", text = "", fg = "#5c5f77" },
	{ name = "pyi", text = "", fg = "#df8e1d" },
	{ name = "pyo", text = "", fg = "#5c5f77" },
	{ name = "pyw", text = "", fg = "#1e66f5" },
	{ name = "pyx", text = "", fg = "#1e66f5" },
	{ name = "query", text = "", fg = "#df8e1d" },
	{ name = "rar", text = "", fg = "#df8e1d" },
	{ name = "rmd", text = "", fg = "#1e66f5" },
	{ name = "rss", text = "", fg = "#df8e1d" },
	{ name = "sc", text = "", fg = "#d20f39" },
	{ name = "scala", text = "", fg = "#d20f39" },
	{ name = "sh", text = "", fg = "#5c5f77" },
	{ name = "sig", text = "", fg = "#df8e1d" },
	{ name = "signature", text = "", fg = "#df8e1d" },
	{ name = "sql", text = "", fg = "#5c5f77" },
	{ name = "sqlite", text = "", fg = "#5c5f77" },
	{ name = "sqlite3", text = "", fg = "#5c5f77" },
	{ name = "tgz", text = "", fg = "#df8e1d" },
	{ name = "tmux", text = "", fg = "#40a02b" },
	{ name = "toml", text = "", fg = "#d20f39" },
	{ name = "torrent", text = "", fg = "#179299" },
	{ name = "ts", text = "", fg = "#1e66f5" },
	{ name = "tsconfig", text = "", fg = "#df8e1d" },
	{ name = "tsx", text = "", fg = "#1e66f5" },
	{ name = "ttf", text = "", fg = "#5c5f77" },
	{ name = "txt", text = "", fg = "#40a02b" },
	{ name = "vim", text = "", fg = "#40a02b" },
	{ name = "wav", text = "", fg = "#1e66f5" },
	{ name = "webm", text = "", fg = "#df8e1d" },
	{ name = "webp", text = "", fg = "#ea76cb" },
	{ name = "wma", text = "", fg = "#1e66f5" },
	{ name = "wmv", text = "", fg = "#df8e1d" },
	{ name = "xls", text = "", fg = "#40a02b" },
	{ name = "xlsx", text = "", fg = "#40a02b" },
	{ name = "xml", text = "", fg = "#df8e1d" },
	{ name = "xpi", text = "", fg = "#d20f39" },
	{ name = "xz", text = "", fg = "#df8e1d" },
	{ name = "yaml", text = "", fg = "#5c5f77" },
	{ name = "yml", text = "", fg = "#5c5f77" },
	{ name = "zip", text = "", fg = "#df8e1d" },
	{ name = "zsh", text = "", fg = "#40a02b" },
]
